# file: "MCL/config/net.mamoe.mirai-api-http/setting.yml"
adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: hcytsl # 你可以自己设定, 这里作为示范
singleMode: false
cacheSize: 4096 # 可选, 缓存大小, 默认4096. 缓存过小会导致引用回复与撤回消息失败
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: 0.0.0.0
    port: 8080 # 端口
    cors: [*]

  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: 0.0.0.0
    port: 8080 # 端口
    reservedSyncId: -1 # 确保为 -1

